---

# all the things

- name: Configure my home lab systems
  hosts: all

  pre_tasks:

    - name: Verify if distro is supported
      ansible.builtin.fail:
        msg: "This playbook is not compatible with the host's distribution."
      when: >
        (ansible_distribution != "Rocky" or ansible_distribution_major_version != "9") and
        (ansible_distribution != "Ubuntu" or ansible_distribution_major_version != "22")

  tasks:

    - name: Include common role
      ansible.builtin.include_role:
        name: common
      tags:
        - install
        - upgrade

# EOF
