# all the things

- hosts: all

  pre_tasks:

    - name: verify if distro is supported
      fail:
        msg: "The host's distribution is not supported."
      when: >
        (ansible_distribution != "Rocky" or ansible_distribution_major_version != "9") and
        (ansible_distribution != "Ubuntu" or ansible_distribution_major_version != "22")

  tasks:

    - name: include common role
      include_role:
        name: common

# EOF
