---

# handlers file for common

- name: Reload firewalld
  become: true
  ansible.builtin.service:
    name: firewalld
    state: reloaded
  listen: "reload firewalld"

- name: restart ssh
  become: true
  ansible.builtin.service:
    name: "{{ ssh_service_name }}"
    state: restarted

# EOF
