---

# handlers file for common

- name: reload firewalld
  become: yes
  ansible.builtin.service:
    name: firewalld
    state: reloaded
  listen: "reload firewalld"

- name: restart sshd
  become: yes
  ansible.builtin.service:
    name: sshd
    state: restarted
  listen: "restart sshd"

# EOF
