---

# handlers file for common

- name: reload firewalld
  service:
    name: firewalld
    state: reloaded
  listen: "reload firewalld"

- name: restart sshd
  service:
    name: firewalld
    state: restarted
  listen: "restart sshd"

# EOF
