---

# handlers file for common

- name: Reload firewalld
  become: true
  ansible.builtin.service:
    name: firewalld
    state: reloaded
  listen: "reload firewalld"

- name: Restart sshd
  become: true
  ansible.builtin.service:
    name: sshd
    state: restarted
  listen: "restart sshd"

- name: Restart ssh
  become: true
  ansible.builtin.service:
    name: ssh
    state: restarted
  listen: "restart ssh"

# EOF
