---

- name: Install base packages
  become: true
  block:

    - name: Install epel-release repo
      ansible.builtin.dnf:
        name: epel-release
        state: present

    - name: Install base required packages
      ansible.builtin.dnf:
        name:
          - bind-utils
          - bzip2
          - chrony
          - cockpit-pcp
          - curl
          - dnf-automatic
          - htop
          - iproute
          - logrotate
          - logwatch
          - net-tools
          - nfs-utils
          - policycoreutils
          - policycoreutils-python-utils
          - rkhunter
          - rsync
          - rsyslog
          - screen
          - tar
          - vim
          - wget
          - yum-utils
          - zip
        state: present

# end of base packages block

# EOF
