---

- name: Install base packages
  become: true
  block:

    - name: Install qemu agent (if virtual)
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: present
        update_cache: true
      when: ansible_virtualization_role == "guest"

    - name: Install base required packages
      ansible.builtin.apt:
        name:
          - bzip2
          - curl
          - htop
          - logrotate
          - logwatch
          - net-tools
          - nfs-common
          - rkhunter
          - rsync
          - rsyslog
          - screen
          - tar
          - vim
          - wget
        state: present
        update_cache: true

# end of base packages block

# EOF
