---

- name: Configure ufw
  become: true
  block:

    - name: Allow ssh
      community.general.ufw:
        rule: allow
        name: OpenSSH

    - name: Enable ufw
      community.general.ufw:
        state: enabled

    - name: Deny everything by default
      community.general.ufw:
        default: deny

# end of ufw block

# EOF
