---

- name: set up firewalld in rocky
  become: true
  block:

    - name: remove services from public zone
      ansible.posix.firewalld:
        zone: public
        service: "{{ item }}"
        permanent: true
        state: disabled
      notify: reload firewalld
      with_items:
        - cockpit
        - dhcpv6-client

    - name: add local subnet source to internal zone
      ansible.posix.firewalld:
        zone: internal
        source: 192.168.1.0/24
        permanent: true
        state: enabled
      notify: reload firewalld

    - name: add services to internal zone
      ansible.posix.firewalld:
        zone: internal
        service: "{{ item }}"
        permanent: true
        state: enabled
      notify: reload firewalld
      with_items:
        - cockpit
        - ssh

    - name: remove ssh service from public zone
      ansible.posix.firewalld:
        zone: public
        service: ssh
        permanent: true
        state: disabled
      notify: reload firewalld

# end of firewalld block

# EOF
