---
# tasks file for common

- name: Include upgrade all packages task
  ansible.builtin.include_tasks:
    file: "update.yml"
    apply:
      tags:
        - upgrade
        - install
  tags:
    - upgrade
    - install

- name: Include install base packages task
  ansible.builtin.include_tasks:
    file: "basepackages-{{ ansible_distribution }}.yml"
    apply:
      tags:
        - install
  tags:
    - install

#- name: include selinux task
#  ansible.builtin.include_tasks:
#    file: "selinux.yml"
#    apply:
#      tags:
#        - install
#  tags:
#    - install
#  when: ansible_distribution == "Rocky"

- name: Include ssh task
  ansible.builtin.include_tasks:
    file: "ssh.yml"
    apply:
      tags:
        - install
  tags:
    - install

- name: Include firewall task
  ansible.builtin.include_tasks:
    file: "firewall-{{ ansible_distribution }}.yml"
    apply:
      tags:
        - install
  tags:
    - install

# EOF
