---
# tasks file for common

- name: include upgrade all packages task
  include_tasks:
    file: "update-{{ ansible_distribution }}.yml"
  tags: upgrade

- name: include install base packages task
  include_tasks:
    file: "basepackages-{{ ansible_distribution }}.yml"
  tags: baseinstall

# EOF
