---
# tasks file for common

- name: include upgrade all packages task
  include_tasks:
    file: "update-{{ ansible_distribution }}.yml"
  tags: upgrade

- name: include install base packages task
  include_tasks:
    file: "basepackages-{{ ansible_distribution }}.yml"
  tags: baseinstall

- name: include ssh task
  include_tasks:
    file: "ssh.yml"
  tags: baseinstall

- name: include firewall task
  include_tasks:
    file: "firewall-{{ ansible_distribution }}.yml"
  tags: baseinstall

# EOF
