---

# disable selinux

- name: disable selinux
  become: yes
  block:

    - name: disable selinux
      ansible.posix.selinux:
        state: disabled

    - name: reboot host
      reboot:

# end of disable selinux block

# EOF
