---

# disable selinux

- name: Disable selinux
  become: true
  block:

    - name: Set selinux to disabled
      ansible.posix.selinux:
        state: disabled

    - name: reboot host
      reboot:

# end of disable selinux block

# EOF
