---

- name: Upgrade all packages
  become: true
  ansible.builtin.dnf:
    name: "*"
    state: latest
  when: ansible_distribution == "Rocky"

- name: Upgrade all packages
  become: true
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
  when: ansible_distribution == "Ubuntu"

# EOF
