---

- name: Upgrade all packages
  become: true
  ansible.builtin.dnf:
    name: "*"
    state: latest
  when: ansible_facts["distribution"] == "Rocky"

- name: Upgrade all packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: yes
  when: ansible_facts["distribution"] == "Ubuntu"

# EOF
